apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: temp-guestbook-app-of-apps
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/34fathombelow/temp.git
    path: apps
    targetRevision: HEAD
  destination:
    name: in-cluster
  syncPolicy:
    automated:
      prune: true
      selfHeal: true  
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - ApplyOutOfSyncOnly=true
      - PruneLast=true