apiVersion: batch/v1
kind: Job
metadata:
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
  name: after
spec:
  backoffLimit: 0
  template:
    spec:
      containers:
      - command:
        - sleep
        - "10"
        image: alpine:latest
        name: sleep
      restartPolicy: Never
