apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: kargo-guestbook
  namespace: kargo-guestbook
spec:
  freightCreationPolicy: Automatic
  interval: 5m0s
  subscriptions:
    - git:
        branch: main
        commitSelectionStrategy: NewestFromBranch
        discoveryLimit: 20
        includePaths:
          - kustomize-guestbook
        repoURL: https://github.com/34fathombelow/temp.git
        strictSemvers: true